clc; clear;

model = 'BMS_Visual_Digital_Twin';

% Close if already open
if bdIsLoaded(model)
    close_system(model,0);
end

% Create model
new_system(model);
open_system(model);

%% ================== INPUT SIGNALS ==================
% SOC input
add_block('simulink/Sources/In1',[model '/SOC'],...
    'Position',[30 50 60 70]);

% SOH input
add_block('simulink/Sources/In1',[model '/SOH'],...
    'Position',[30 120 60 140]);

% TEMP input
add_block('simulink/Sources/In1',[model '/TEMP'],...
    'Position',[30 190 60 210]);

%% ================== BATTERY BODY ==================
add_block('simulink/Commonly Used Blocks/Subsystem',...
    [model '/Battery_Pack'],...
    'Position',[150 40 350 260]);

open_system([model '/Battery_Pack']);

% Battery background
add_block('simulink/Sinks/Display',...
    [model '/Battery_Pack/Battery_Display'],...
    'Position',[60 60 160 100]);

set_param([model '/Battery_Pack/Battery_Display'],...
    'ForegroundColor','black',...
    'BackgroundColor','green');

%% ================== SOC BAR ==================
add_block('simulink/Dashboard/Linear Gauge',...
    [model '/SOC_Gauge'],...
    'Position',[400 40 520 120]);

set_param([model '/SOC_Gauge'],...
    'Limits','[0 100]',...
    'Label','SOC (%)');

%% ================== SOH BAR ==================
add_block('simulink/Dashboard/Linear Gauge',...
    [model '/SOH_Gauge'],...
    'Position',[400 140 520 220]);

set_param([model '/SOH_Gauge'],...
    'Limits','[0 100]',...
    'Label','SOH (%)');

%% ================== TEMP GAUGE ==================
add_block('simulink/Dashboard/Circular Gauge',...
    [model '/TEMP_Gauge'],...
    'Position',[580 80 700 200]);

set_param([model '/TEMP_Gauge'],...
    'Limits','[0 80]',...
    'Label','Temp (°C)');

%% ================== WARNING LAMPS ==================
add_block('simulink/Dashboard/Lamp',...
    [model '/SOC_Warning'],...
    'Position',[750 40 800 90]);

set_param([model '/SOC_Warning'],...
    'Label','SOC LOW');

add_block('simulink/Dashboard/Lamp',...
    [model '/TEMP_Warning'],...
    'Position',[750 140 800 190]);

set_param([model '/TEMP_Warning'],...
    'Label','TEMP HIGH');

%% ================== LOGIC BLOCKS ==================
% SOC < 20%
add_block('simulink/Logic and Bit Operations/Compare To Constant',...
    [model '/SOC_Compare'],...
    'Position',[200 50 300 90],...
    'const','20',...
    'relop','<');

% TEMP > 50
add_block('simulink/Logic and Bit Operations/Compare To Constant',...
    [model '/TEMP_Compare'],...
    'Position',[200 190 300 230],...
    'const','50',...
    'relop','>');

%% ================== CONNECTIONS ==================
add_line(model,'SOC/1','SOC_Gauge/1');
add_line(model,'SOH/1','SOH_Gauge/1');
add_line(model,'TEMP/1','TEMP_Gauge/1');

add_line(model,'SOC/1','SOC_Compare/1');
add_line(model,'SOC_Compare/1','SOC_Warning/1');

add_line(model,'TEMP/1','TEMP_Compare/1');
add_line(model,'TEMP_Compare/1','TEMP_Warning/1');

%% ================== SAVE ==================
save_system(model);

disp('✅ BMS Visual Digital Twin Simulink model created successfully');
